title: Unfold Collective
author:
  name: Unfold Collective
metadata:
    description: 'A creative studio designing on the intersection of digital and physical media'

# Header customization
header:
  title: Unfold<span>Collective</span>
  description: A creative studio designing on the intersection of digital and physical media
  buttons:
    # - text: "Back to the article"
    #   link: "http://tympanus.net/codrops/?p=19439"
    #   class: "learn-more-btn"

footer:
  links:
    - text: 🌞 Hope you're having a nice day!
      # url: "#"
    # - text: Legals
    #   url: "#"
